query {
        topBarCollection {
            items {
                className
                logo {
                    classname
                    title
                    href
                }
                navigationBarCollection {
                    items {
                        classname
                        title
                        url
                    }
                }
            }
        }
    }